buildscript {
    repositories { google() ; mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:8.2.2' }
}

allprojects {
    repositories { google() ; mavenCentral() }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.kittu.pawfect'
    compileSdk 34
    defaultConfig {
        applicationId "com.kittu.pawfect"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
